version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
  pre_build:
    commands:
      - echo "S3_BUCKET_NAME               = ${S3_BUCKET_NAME}"
      - echo "CLOUDFRONT_ID                = ${CLOUDFRONT_ID}"
      - echo "CLOUDFONT_INVALIDATION_PATHS = ${CLOUDFONT_INVALIDATION_PATHS}"
  build:
    commands:
      - echo "test build"
      - ls -l build/
  post_build:
    commands:
      - cd build
      - ls -l
      - cd ../
      - ls -l
#      - mv build admin
#      - ls -l admin/
#      - aws s3 sync build/ s3://kamada-test2/admin --delete
#      - aws s3 sync admin/ s3://kamada-test2/admin --delete --exclude "build/*"
#      - aws s3 sync build s3://kamada-test2/codedeploy-test/build --delete
