version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
  pre_build:
    commands:
      - node -v
  build:
    commands:
      - echo "test build"
      - ls -l
      - aws s3 sync build s3://kamada-test2/codedeploy-test/build --delete
